language: node_js
node_js:
  - "8.11.0"
after_success: |
  if [ -n "$GITHUB_API_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    npm run compile-docs
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='smcelhinney' -c user.email='stephen@appstruct.io' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://smcelhinney:$GITHUB_API_TOKEN@github.com/HubSpotWebTeam/hs-node-api gh-pages:gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
before_deploy: "echo 'Deploying new npm package'"
before_deploy:
  - echo 'Tagging TRAVIS build'
  # Set up git user name and tag this commit, fix this for other users
  - git config --local user.name "smcelhinney"
  - git config --local user.email "stephen@appstruct.io"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: npm
  email: smcelhinney@hubspot.com
  api_key: $NPM_TOKEN
  on:
    branch: release
    repo: HubSpotWebTeam/hs-node-api